# Generated by Django 4.2 on 2023-05-04 12:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_rename_dolist_dlist_rename_todolist_tdlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DList',
            new_name='DoList',
        ),
        migrations.RenameModel(
            old_name='TDList',
            new_name='ToDoList',
        ),
    ]
